# Website settings
url: "https://richardgonlag.nl"

# Internal nav
nav:
  main:
    projecten: "/projects"

# Bio settings
name: "Richard Gonlag"
description: "De homepagina van Richard Gonlag."
thumbnail_path: "profile-photos/richard-gonlag-medium.jpg"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/RGonlag"
    label: "Twitter"
    icon: "twitter-square"
    username: "@RGonlag"
  linkedin:
    url: "https://www.linkedin.com/in/richard-gonlag"
    label: "LinkedIn"
    icon: "linkedin-square"
  # facebook:

  # google:

  # slideshare:

  github:
    url: "https://github.com/r8420/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:mail@richardgonlag.nl"
    label: "Email"
    value: "mail@richardgonlag.nl"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'


# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
